flowchart TB
    %% Documentation: https://mermaid-js.github.io/mermaid/#/flowchart
    %% To generate png file: mmdc -i <source>.mmd -o <target>.png

    MENU(("/menu")):::entryPoint -->|Current active notifications...| CHOOSING((CHOOSING)):::state


    CHOOSING ==> guild("Discord guild"):::userInput
    CHOOSING ===> roles("Discord roles"):::userInput
    CHOOSING ===> channels("Discord channels"):::userInput
    CHOOSING ==> handle("Discord handle"):::userInput
    CHOOSING ==> delete("Delete my data"):::userInput
    CHOOSING ==> done("Done"):::userInput

    handle ----> |"Please enter your <br /> Discord username ..."| TYPING_REPLY
    guild ----> |"Please enter a <br /> guild ID ..."| TYPING_REPLY
    roles --> submenu("Inline button menu: <br /> | Add | Remove | Back |"):::inlineMenu
    channels --> submenu
    delete --> |"Data successfully wiped! <br /> Hit /menu to start over."| End
    done --> |"Bring back the /menu anytime!"| End(("END")):::termination

    submenu ---> |"[save button press] <br /> Please enter the name <br /> of a role / channel ..."| TYPING_REPLY((TYPING_REPLY)):::state
    submenu --> |"[if 'Back']"| MENU

    add_remove_more --> |"[if 'Add/Remove more']"| TYPING_REPLY
    add_remove_more --> |"[if 'Back']"| MENU

    TYPING_REPLY --> |"[if coming from inline button menu: <br /> store/delete data according to logic in <br /> received_callback()]"| add_remove_more("Inline button menu: <br /> | Add/Remove more? | Back |"):::inlineMenu
    TYPING_REPLY --> |"[save choice: text] <br /> [store/delete data according to logic in <br /> received_information()] "| MENU

    classDef userInput fill:#2a5279, color:#ffffff, stroke:#ffffff
    classDef inlineMenu fill:#ffff66, color:#000000, stroke:#ffffff
    classDef state fill:#222222, color:#ffffff, stroke:#ffffff
    classDef entryPoint fill:#009c11, stroke:#42FF57, color:#ffffff
    classDef termination fill:#bb0007, stroke:#E60109, color:#ffffff
